### ISSUE TITLE
Add .jpg to picture URLs

### ISSUE THREAD

**Issue by iquito** [padyx/purplemoon-android#127]
Purplemoon is now running through Cloudflare - and Cloudflare only caches pictures by extension. That is why I have added a .jpg everywhere in the API for picture URLs. If the App just adds a .jpg on every picture URL, then the response will be faster and CDN-cached.

The documentation (api.panaxis.ch/v1) was also updated to include the .jpg endings :-)

**Comment by padyx** [comment]
Ok, good to know. But I can't see the change in the documentation yet at the URL you provided. 
But I'll extrapolate from the urls on the webpage ;)
