### ISSUE TITLE
Development without API

### ISSUE THREAD

**Issue by Electric-9** [padyx/purplemoon-android#130]
Is there a way to develop with an API without rewriting the PurplemoonAPIAdapter? Like a dummy key or a purplemoon clone or something?

**Comment by padyx** [comment]
I don't quite follow - what do you mean by "without rewriting the PurplemoonAPIAdapter"?

Currently there is no test server available on the Purplemoon side.
Development of  this app actually done with the productive api key, which needs to be requested from Purplemoon - and thus can't be checked in here...

**Comment by Electric-9** [comment]
The PurplemoonAPIAdapter is used to abstract the Purplemoon API. It allows to implement another adapter which can provide sample data to power the app with sample data - without the API.

I dont want to develop on a productive system. I would need dummy users, which is not allowed by Purplemoon

But I thank for the information.
